### ISSUE TITLE
Skipping differential expression filtering with overclustering

### ISSUE THREAD

**Issue by HJ-UCSD** [madsen-lab/valiDrops#11]
My team is really impressed by Validrops and have been using it in our projects recently. However, would it be possible to add a paramater in the initial Validrops call to skip certain steps in the process? We noticed we lose a lot of barcodes in the differential expression filtering step presumably because our data is relatively homogeneous. Thank you again for developing this program!

**Comment by JesperGrud** [comment]
Thank you for the great suggestion. I have added it to our todo list, and will comment here once it is implemented. ETA in August most likely.

**Comment by JesperGrud** [comment]
This has now finally been implemented. You can set stageThree = FALSE to skip stage 3 of valiDrops
