### ISSUE TITLE
Possibility of Creating a QC Function for snATAC Data?

### ISSUE THREAD

**Issue by Sandman-1** [madsen-lab/valiDrops#16]
Hello! Thank you for such an awesome package. Is there a possibility of creating a similar function/package for quality control on single-cell ATAC sequencing data?

**Comment by JesperGrud** [comment]
Hi Sandman-1. I'm glad that you are finding valiDrops as a good tool for your research. We currently do not have the bandwidth to develop a variant suitable for single-cell ATAC-sequencing data internally.
